### ISSUE TITLE
Plugin doesn't work with node.js 0.10 

### ISSUE THREAD

**Issue by juliandescottes** [attester/attester-maven-plugin#5]
Hi,

Just tried installing the plugin, copied node.exe in the scripts folder ... But when running <code>mvn clean test</code> on the sample application in attester-maven-plugin it was failing on a <code>path.join</code>. 

_I tried to track back the root of the error and it looks like the root directory of the tests is missing from the configuration passed to attester cli.js. But I wouldn't trust myself too much on this one, my investigation was messy._

Then I uninstalled node __0.10__ and reinstalled node __0.8.8__ and it worked.

Same issue was reproduced on another machine where node was never installed. 

__Edit__ : Exact version of Node used was 0.10.5 . Not sure if the issue is coming from Node or from the plugin ...

**Comment by divdavem** [comment]
I am closing this issue now that attester works fine with node.js 0.10.
(cf attester/attester#27 and de3ffac495134bd894fda538a4474ce26237bc4b)
